# Generated by Django 2.2.28 on 2023-10-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_auto_20230915_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='user',
        ),
    ]
