# Generated by Django 2.2.28 on 2023-09-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
